
import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";

// Helper function to extract base64 data and mime type from data URL
const parseDataUrl = (dataUrl: string): { mimeType: string; data: string } => {
  const parts = dataUrl.split(',');
  const meta = parts[0];
  const data = parts[1];
  const mimeType = meta.match(/:(.*?);/)?.[1] || 'image/jpeg';
  return { mimeType, data };
};

export const generateEditedImage = async (
  base64Images: string[],
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const imageParts = base64Images.map(img => {
    const { mimeType, data } = parseDataUrl(img);
    return {
      inlineData: {
        data,
        mimeType,
      },
    };
  });

  const textPart = {
    text: prompt,
  };

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [...imageParts, textPart],
      },
      config: {
          responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const { data, mimeType } = part.inlineData;
        return `data:${mimeType};base64,${data}`;
      }
    }
  } catch(e) {
    console.error(e);
    throw new Error("Failed to generate image. Please check your prompt and uploaded images.");
  }

  throw new Error("No image was generated by the API.");
};
