import { GoogleGenAI, Modality } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";
import type { Page } from '../App';

// Helper function to extract base64 data and mime type from data URL
const parseDataUrl = (dataUrl: string): { mimeType: string; data: string } => {
  const parts = dataUrl.split(',');
  const meta = parts[0];
  const data = parts[1];
  const mimeType = meta.match(/:(.*?);/)?.[1] || 'image/jpeg';
  return { mimeType, data };
};

export type AspectRatio = '3:4' | '1:1' | '16:9';


export const generateImage = async (
  mode: Page,
  base64Images: string[],
  prompt: string,
  aspectRatio: AspectRatio
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  if (mode === 'textToImage') {
    // Use Imagen for high-quality text-to-image generation
    try {
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: aspectRatio,
        },
      });

      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } catch(e) {
      console.error(e);
      throw new Error("Failed to generate image with Imagen. Please check your prompt.");
    }

  } else {
    // Use Gemini for image editing and other tasks
    const imageParts = base64Images.map(img => {
      const { mimeType, data } = parseDataUrl(img);
      return {
        inlineData: {
          data,
          mimeType,
        },
      };
    });

    const textPart = {
      text: prompt,
    };

    try {
      const response: GenerateContentResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [...imageParts, textPart],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
      });

      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const { data, mimeType } = part.inlineData;
          return `data:${mimeType};base64,${data}`;
        }
      }
      throw new Error("No image was generated by the API.");
    } catch(e) {
      console.error(e);
      if (e instanceof Error) {
        throw new Error(`Failed to generate image. ${e.message}`);
      }
      throw new Error("Failed to generate image. Please check your prompt and uploaded images.");
    }
  }
};